#声明端口
server:
  port: 8081
spring:
  profiles:
    #  选择使用哪个配置文件
    active: dev
mybatis:
  ## Mybatis 配置
  #mybatis.type-aliases-package 配置为 org.spring.springboot.domain，指向实体类包路径。
  #mybatis.mapper-locations 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件。
  type-aliases-package: com.demo.jdbc.model
  mapper-locations: classpath:mapper/*.xml
    #  开启驼峰
  configuration:
    map-underscore-to-camel-case: true
#输出sql语句
logging:
  level:
    com:
      demo:
        jdbc:
          dao: debug
